[package]
name = "my_rust_demo"
version = "0.1.0"
authors = ["HuangJinAmm <422837038@qq.comm>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
